### PR TITLE
Initial test pipelines

### PR DESCRIPTION
**Pull request by bsquizz**

### CODE REVIEW

**Comment by bsquizz** [comment]
smoke test please

**Comment by bsquizz** [comment]
smoke test please

**Comment by bsquizz** [comment]
Whew I had fun getting the pip install for this to work on the jenkins-slave-base-centos7 image, the fastparquet build kept failing, finally got it working by installing this extra devel stuff:
```
RUN yum makecache && \
    yum install -y epel-release && \
    yum install -y yum-utils snappy-devel python36 python36-setuptools python36-devel gcc gcc-c++ && \
    yum-config-manager --enable extras && \
    yum makecache && \
    yum install -y clang && \
    yum clean all -y
```

This is ready now too

**Comment by tumido** [comment]
@AparnaKarve Travis is not out of picture at all. We're gonna keep that for unit testing and linting. I don't want to give up the steering wheel completely, since:
1. We're still responsible for unit testing and code quality.
2. Travis and Jenkins can work together. It may seem like there is complete redundancy, and that's fine. 3. We have to keep in mind that AI Ops is intended for other purposes than just Insights, though this Jenkins setup is tied to insights OpenShift clusters, but we need to be capable working outside of that.
4. You need `insights-dev` cluster credentials to view the test results from Jenkins. Travis is open by default.

**Comment by AparnaKarve** [comment]
@tumido Ok, all good points above of why Travis should still be around - I don't mind the redundancy at all.

I was just going by this, and did not see Travis CI, hence the assumption that we would not be using Travis -

screen shot 2018-11-08 at 8 27 22 am

**Comment by tumido** [comment]
@AparnaKarve yes, that's just because we don't have Travis available for this dummy-ai repo yet (all the others are enabled, this is the only one missing). :wink:

**Pull request merged**
