### PR TITLE
Ping both Redis and also Next Service for a complete liveness/readiness check

### PR DESCRIPTION
**Pull request by AparnaKarve**
In addition to pinging the required service `Redis`, also ping `Next Service` (AI service), which completes the requirement of Liveness/Readiness health probe checks for aiops-data-collector

Fixes [AIOPS-119](https://projects.engineering.redhat.com/browse/AIOPS-119)

Requires https://github.com/ManageIQ/aiops-ai-library/pull/43 for Volume Type Validation

### CODE REVIEW

**Comment by AparnaKarve** [comment]
While I realize what you mean, IMO,  Readiness should take into account that all the dependencies are available, before making the container ready. 
Imagine a situation where the data collector has completed a long running data collection operation (30+ minutes or 40+ minutes), only to find out later that the Next Service was not configured correctly or was not available...
--> making the entire data collection operation a wasted cycle, something that could have been easily avoided by pinging the Next service upfront.

So how about we do this?
Instead of using probes, lets at least do an initial configuration check in data collector to check for the availability of Next Service (by pinging it first)


-----------
On a slightly different note, ideally the collected data should be saved in a storage bucket after every successful run, ensuring that the data collection operation is not wasted.
(i.e. if we are not fetching data directly from the datahub, and instead using the data collector)

When we start using Kubeflow, let's look into storing the output of key microservices (like data collector) in a storage bucket.

**Comment by tumido** [comment]
With Kubeflow, this workflow would be totally redundant since the task in Argo workflow would manage this completely differently. And yeah, a object storage is the preferred way to pass data, I agree.

Besides that. I still don't think we should wait for publisher/ai service to become ready so we can make another service ready. This creates a new chain of dependencies. Imagine a scenario - publisher is not ready. We already know that, since its readiness probe failed. So we have a warning that there's something wrong with publisher. Now, with the probes approach used in this PR, it would mean every service in the pipeline is raising a warning and none of the services is ready. That doesn't help. The opposite approach, when only one service is failing brings much better visibility into the problem. It identifies the problematic part in plain sight. No need to go and check why every single pod is failing... 

Because.. when a readiness probe fails, it doesn't tell you on listener service that it's because publisher service is not ready. It creates a great level of confusion. And the purpose of these probes are to quickly identify the problem.

Also when readiness probe fails many times, it restarts the pod. So because of e.g. failing publisher the whole pipeline is restarting etc.

This is one of the key ideas in microservice architecture - break the app into the smallest parts that can operate separately and when one piece fail, it's easy to recover, identify and investigate the issue. The probes, you're suggesting, make the pipeline fail as a whole and goes against this principle. I don't recommend that.

**Comment by AparnaKarve** [comment]
Yes, with re-architecture and kubeflow, argo etc, the entire landscape of our pipeline would change.

What do you think about pinging the Next Service just as an initial configuration check? No need for probes. 
That way at least [AIOPS-119](https://projects.engineering.redhat.com/browse/AIOPS-119) gets addressed.

**Comment by tumido** [comment]
I wouldn't care about the next service at all. I would care about Redis for the probe. That's good, I like that part. And maybe as I'm thinking about the initial check - what about checking the topological and host inventory presence?

The point I have in mind for not checking the next service as part of the initial startup: Imagine the pipeline being deployed as new (or redeployed via jenkins, etc.) All services are starting together at the same time. So that means, the next service is not available in the time this service is starting. And that would result in this service failing the check and going into the restart... I'm not sure what such chain reaction might result into. I can see the only possible outcome that ocdeployer can have - hanging job which results into a failed jenkins job...

**Comment by AparnaKarve** [comment]
Alright, all fair points!

Re-architecure/Kubeflow should take care of the issue that I mentioned above https://github.com/ManageIQ/aiops-data-collector/pull/46#issuecomment-510973827 by using object storage/s3 buckets etc

So in light of all the points laid above, I'm closing this PR.
Thanks @tumido

**Pull request closed without merging**
